const cardsDataArray = [
  {
    inventoryType: "SOLD OUT",
    img: "Katie-Zaferes",
    stars: "5.0",
    reviewsNum: 6,
    country: "USA",
    title: "Life lessons with Katie Zaferes",
    price: 136,
  },
  {
    inventoryType: "ONLINE",
    img: "wedding-photography",
    stars: "5.0",
    reviewsNum: 30,
    country: "USA",
    title: "Learn wedding photography",
    price: 125,
  },
  {
    img: "mountain-bike",
    stars: "4.8",
    reviewsNum: 2,
    country: "USA",
    title: "Group Mountain Biking",
    price: 50,
  },
  {
    inventoryType: "SOLD OUT",
    img: "Katie-Zaferes",
    stars: "5.0",
    reviewsNum: 6,
    country: "USA",
    title: "Life lessons with Katie Zaferes",
    price: 136,
  },
  {
    inventoryType: "ONLINE",
    img: "wedding-photography",
    stars: "5.0",
    reviewsNum: 30,
    country: "USA",
    title: "Learn wedding photography",
    price: 125,
  },
  {
    img: "mountain-bike",
    stars: "4.8",
    reviewsNum: 2,
    country: "USA",
    title: "Group Mountain Biking",
    price: 50,
  },
  {
    inventoryType: "SOLD OUT",
    img: "Katie-Zaferes",
    stars: "5.0",
    reviewsNum: 6,
    country: "USA",
    title: "Life lessons with Katie Zaferes",
    price: 136,
  },
  {
    inventoryType: "ONLINE",
    img: "wedding-photography",
    stars: "5.0",
    reviewsNum: 30,
    country: "USA",
    title: "Learn wedding photography",
    price: 125,
  },
  {
    img: "mountain-bike",
    stars: "4.8",
    reviewsNum: 2,
    country: "USA",
    title: "Group Mountain Biking",
    price: 50,
  },
];

export { cardsDataArray };
